// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import 'normalize.css'
import axios from 'axios'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
import VueI18n from 'vue-i18n'
import App from './App'
import router from './router'

Vue.config.productionTip = false

const locales = {
  en: {
    loginregister: 'login/register',
    login: 'login',
    register: 'register',
    home: 'Home',
    exit: 'exit',
    error: 'server exception, please retry later',
    hint: 'hint',
    confirm: 'confirm',
    registerEmailMsg: 'your email registered successfully, you can login directly and complete detail later',
    menu: {
      changemakers: 'For Changemakers',
      investors: 'For Investors',
      media: 'Media',
      others: 'For Others',
    },
    subMenu: {
      interview: 'look for publicity',
      interviewDes: 'opportunity to appear on Diinsider home page',
      findInvestor: 'look for investment',
      findInvestorDes: 'identify your best match',
      consult: 'consult',
      consultDes: 'consult',
      accreditation: 'apply for accreditation',
      accreditationDes: 'easier to attract investors after accreditation',
      findProject: 'look for programs',
      findProjectDes: 'identify your best match',
      investDiinsider: 'invest Diinsider',
      investDiinsiderDes: 'Diinsider is also a changemaker',
      customized: 'customized research',
      customizedDes: 'market/project due diligence, to assist your investment decision',
      background: 'background knowledge',
      backgroundDes: 'changemakers, international development and investment',
      change: 'CHANGE',
      changeDes: 'tell story to the world',
      opportunity: 'opportunity update',
      opportunityDes: 'opportunity of innovating',
      events: 'events update',
      eventsDes: 'acquire the events up to minute',
    },
    search: 'search',
    loginForm: {
      email: 'please input email',
      emailValid: 'email can\'t be empty',
      password: 'please input password',
      passwordValid: 'password can\'t be empty',
      forget: 'forget password',
    },
    registerForm: {
      basic: 'basic data',
      choose: 'choose role',
      accreditation: 'accreditation',
      email: 'email',
      emailMsg: 'please input email',
      emailValid: 'email can\'t be empty',
      password: 'password',
      passwordMsg: 'please input password',
      passwordValid: 'password can\'t be empty',
      confirm: 'cofirm password',
      confirmMsg: 'please input password again',
      confirmValid: 'the two password can\'t match',
      next: 'next',
      individual: 'individual ',
      changemaker: 'changemaker',
      investor: 'investor',
      others: 'others',
      skip: 'skip, choose later',
      back: 'back',
      chooseValid: 'if you don\'t want to choose role now, click skip',
      chooseMsg: 'choose role, you can unlock more function',
      name: 'name of organization',
      nameMsg: 'please input name of organization',
      nameValid: 'name of organization can\'t be empty',
      education: 'education',
      environment: 'environment',
      health: 'health',
      agriculture: 'agriculture',
      energy: 'renewable energy',
      finance: 'inclusive finance',
      gender: 'gender equity',
      other: 'other, please specify',
      least: 'please choose one at least',
      sectorMsg: 'please input sector',
      foundedMsg: 'choose the date organization founded',
      locationMsg: 'please input the location projects develop mainly',
      grant: 'grant/donation',
      loan: 'loan/debt',
      equity: 'equtiry investment',
      self: 'self-sustained',
      fundingMsg: 'please input source of funding',
      revenue: 'Is your project generating revenue now?',
      assistant: 'assistant needed',
      assistance: 'What kinds of assistance do you need?',
      assis: {
        business: 'business model development',
        brand: 'branding and communication',
        program: 'program management',
        impact: 'impact investment',
        market: 'market accessibility',
        date: 'date management',
        partner: 'partnership opportunities',
        human: 'human resources',
        monitor: 'monitoring and evaluation',
      },
      assisMsg: 'please input assistant needed',
      resource: 'How do you know about Diinsider?',
      resources: {
        website: 'website',
        media: 'media report',
        social: 'social media',
        invited: 'invited by Diinsider',
        referred: 'referred by friends/colleagues',
        conference: 'conference & activities',
      },
      user: 'name',
      userMsg: 'please input your name ',
      numberMsg: 'please input number',
      destinationMsg: 'please input invest destination',
      investTypeMsg: 'please input invest type',
      expect: 'What is your expectation from impact investing?',
      willing: 'invest willing',
      rate: 'Assume the following startup social enterprises approach you, please rate your willingness to invest in them (score from 0 to 9. 0=least willing to invest; 9=most willing to invest), also if you would love to invest, how much?',
      rate1: 'The company focuses in improving community healthcare in Nepal and is estimated worth 1 million USD. Currently, it has passed the first round of investment. Its annual profit is 0.1 million USD. The total number of employee is about 5-10. To what extent are you willing to invest?  Score from 0-9. How much are you willing to invest?',
      rate2: 'The company focuses in providing coding skills development courses for youths in Southern Africa and just has an idea at this stage. They have a primary team that is dedicated to promoting IT education and have been actively sourcing instructors of coding and IT partners. The total number of team members is 5. To what extent are you willing to invest?  Score from 0-9. How much are you willing to invest?',
      rate3: 'The company focuses in improving community sanitation through designing affordable and comfortable toilets for people living in rural Liberia and is in pilot market research stage. Currently, it has not gained profits, but the team members have diverse skills (operation, marketing, design, communications) needed for the success of the program. The team is eager to find their angel investment to expand the current market research. They are confident about their products and expect to have some very positive results in just 6 months, if the investment can help them keep the operation. To what extent are you willing to invest?  Score from 0-9. How much are you willing to invest?',
      rate4: 'The organization is originally a grassroots NGO that is dedicated to promoting quality education for poor children through designing textbooks that are highly interesting and inspiring. Two years ago they started to be interested in the potential of becoming a social enterprise, and with the help of advisors they adopted a new pricing strategy, to deliver books for free to poor children, and at the same time sell books to others that are economically better off. Two year passed and now they have just been able to cover their expenses through this model. They have delivered over 150,000 books and are ambitious to expand this model. To what extent are you willing to invest?  Score from 0-9. How much are you willing to invest?',
      upload: 'upload',
      planMsg1: 'Please upload your project plan, including problem description, solution, clientele, competency/qualification, revenue sources, market potential, competitor analysis, team introduction, social impact KPI.',
      planMsg2: 'support pdf only',
      logo: 'logo',
      logoMsg: 'please upload picture',
      descMsg: 'please describe your project simply',
      complete: 'complete',
    },
    all: 'all',
    sectorDetail: [
      'education',
      'environment',
      'health',
      'agriculture',
      'renewable energy',
      'inclusive finance',
      'gender equity',
    ],
    sector: 'sector',
    destinationDetail: [
      'Asia',
      'Europe',
      'Africa',
      'South America',
      'North America',
      'Oceania',
    ],
    investType: 'invest type',
    org: 'organization',
    desc: 'description',
    representative: 'representative',
    stageDetail: ['idea', 'start up', 'scaling'],
    revenueDetail: ['yes', 'no'],
    budget: 'annual budget',
    fundSource: 'source of funding',
    expect: 'expect',
    returnRate: 'expected return rate',
    investStage: 'invest term',
    investBudget: 'invest range',
    onlySocial: 'Only for social impacts',
    onlyEconomic: 'Only for economic returns',
    bothSocial: 'For both social impacts and economic returns, but social impacts come first',
    bothEconomic: 'For both social impacts and economic returns, but economic returns come first',
    plan: 'plan',
    founded: 'date founded',
    location: 'location',
    stage: 'project stage',
    idea: 'idea',
    start: 'start up',
    scaling: 'scaling',
    staff: 'number of full time staff',
    funding: 'source of funding',
    expertise: 'expertise',
    destination: 'invest destination',
    select: 'invest preference',
    website: 'website',
    noLimit: 'no limit',
    yes: 'yes',
    no: 'no',
    revenueType: 'revenue',
    assistance: 'assistance needed',
  },
  cn: {
    loginregister: '登录/注册',
    login: '登录',
    register: '注册',
    home: '首页',
    exit: '退出',
    error: '服务器异常，请稍后再试',
    hint: '提示',
    confirm: '确认',
    registerEmailMsg: '您的邮箱已经注册成功，您可以先直接登录，稍后再完善资料',
    menu: {
      changemakers: '我是社企',
      investors: '我要投资',
      media: '只是看看',
      others: '其他',
    },
    subMenu: {
      interview: '寻求报道',
      interviewDes: '有机会登上Diinsider首页',
      findInvestor: '投资对接',
      findInvestorDes: '为你找到最匹配的投资人',
      consult: '战略咨询',
      consultDes: '为你提供个性化的功能与服务',
      accreditation: '申请认证',
      accreditationDes: '认证后解锁更多功能，更容易得到投资人青睐',
      findProject: '项目投资',
      findProjectDes: '为您找到最合适的项目',
      investDiinsider: '投资Diinsider',
      investDiinsiderDes: '我们来找最合适的项目',
      customized: '定制研究',
      customizedDes: '项目尽职调查，助力投资决策',
      background: '背景知识',
      backgroundDes: '草根创新、国际发展与影响力投资',
      change: '创变杂志',
      changeDes: '将草根将给世界听',
      opportunity: '机遇动态',
      opportunityDes: '社会创新与新兴市场机遇动态',
      events: '活动速递',
      eventsDes: '了解最新的活动信息',
    },
    search: '搜索',
    loginForm: {
      email: '请输入邮箱',
      emailValid: '邮箱不能为空',
      password: '请输入密码',
      passwordValid: '密码不能为空',
      forget: '忘记密码',
    },
    registerForm: {
      basic: '基础信息',
      choose: '选择角色',
      accreditation: '申请认证',
      email: '邮箱',
      emailMsg: '请输入邮箱',
      emailValid: '邮箱不能为空',
      password: '密码',
      passwordMsg: '请输入登录密码',
      passwordValid: '密码不能为空',
      confirm: '确认密码',
      confirmMsg: '请再次输入登录密码',
      confirmValid: '两次密码不一致',
      next: '下一步',
      individual: '个人用户',
      changemaker: '初创企业',
      investor: '投资者',
      others: '其他机构',
      skip: '暂时不选择，跳过',
      back: '上一步',
      chooseValid: '若不选择角色请点击跳过',
      chooseMsg: '选择角色并完成认证可以解锁更多功能哦',
      name: '机构名称',
      nameMsg: '请输入机构名称',
      nameValid: '机构名称不能为空',
      education: '教育',
      environment: '环境',
      health: '健康',
      agriculture: '农业',
      energy: '可再生资源',
      finance: '普惠金融',
      gender: '性别平等',
      other: '其他，请注明',
      least: '请至少选择一项',
      sectorMsg: '请输入影响领域',
      foundedMsg: '请选择机构创立时间',
      locationMsg: '请输入主要项目开展地点',
      grant: '捐赠',
      loan: '借贷',
      equity: '股权投资',
      self: '自给',
      fundingMsg: '请输入资金来源',
      revenue: '项目目前是否产生收入？',
      assistant: '所需帮助',
      assistance: '您需要哪方面的协助？',
      assis: {
        business: '商业模式开发',
        brand: '品牌推广',
        program: '项目管理',
        impact: '融资',
        market: '市场渠道',
        date: '咨讯信息',
        partner: '合作机会',
        human: '人力资源',
        monitor: '监测评估',
      },
      assisMsg: 'please input assistant needed',
      resource: '如何得知Diinsider?',
      resources: {
        website: '网站',
        media: '媒体报道',
        social: '社交媒体',
        invited: 'Diinsider邀请',
        referred: '朋友/同事推荐',
        conference: '活动会议',
      },
      website: '网址',
      user: '姓名',
      userMsg: '请输入姓名',
      numberMsg: '请输入数字',
      destinationMsg: '请输入投资目的地',
      investTypeMsg: '请输入资金来源',
      expect: '您的机构参与影响力投资的主要目的？',
      willing: '投资意愿',
      rate: '假设以下的初创社会企业联络您，希望了解您是否有意愿对其进行投资，请根据您的意愿对其进行打分（0 到 9，0 代表最不希望投资，9 代表最希望投资）。以及如果希望投资，投资金额为多少？',
      rate1: '该机构专注于改善尼泊尔的社区医疗保健，估值约为 100 万美元。目前已经通过了天使投资。年利润为 10 万美元。员工总数约 20-30 人。你愿意在多大程度上投资？',
      rate2: '该机构专注于为南部非洲的青少年提供程序开发课程，以应对非洲市场对于编程人才的巨大需求。目前该项目只有一个想法，但整个团队对促进 IT 教育非常有热情，并积极寻找适合教授编码课程的导师。团队成员目前总数为 5 人，您愿意在多大程度上投资？',
      rate3: '该机构专注于通过为生活在利比里亚农村的人们设计廉价舒适的厕所服务来改善社区卫生，并在市场调研和项目试点阶段。目前，它还没有获得利润，但是团队成员具有促使该方案成功所需的各种技能（运营，营销，设计，传播）。该团队渴望获得他们的天使投资来维持项目当前的运营。他们对自己的产品充满信心，并期望在接下来 6 个月之内取得一些非常积极的成果。你愿意在多大程度上投资？',
      rate4: '该组织原本是一个草根非营利组织，致力于通过设计有益智性和鼓舞人心的教科书，以帮助贫困儿童获得优质教育。两年前，他们开始对转变为社会企业产生兴趣，并在一些市场顾问的帮助下，采用了新的差异定价策略，向贫穷地区的孩子免费提供书籍，同时向有购买能力的人出售书籍。两年过去了，现在他们已经能够通过这个模式来收回项目成本。他们已经出售或赠送了超过 15 万本书籍，并正在雄心勃勃地扩大这一模式。你愿意在多大程度上投资？分数从 0-9。你愿意投资多少',
      upload: '上传',
      planMsg1: '请上传您的项目计划书，包含问题描述、解决方案、服务群体、竞争优势、收入来源、市场前景、竞争者分析、团队介绍，社会影响力指标',
      planMsg2: '只支持pdf',
      logo: '机构logo',
      logoMsg: '上传图片',
      descMsg: '请简单描述您的项目，便于其他用户搜索到您',
      complete: '完成',
    },
    all: '全部',
    sectorDetail: ['教育', '环境', '健康', '农业', '可再生能源', '小微金融', '性别平等'],
    sector: '关注领域',
    destinationDetail: ['亚洲', '欧洲', '非洲', '南美', '北美', '大洋洲'],
    destination: '投资地点',
    stageDetail: ['设想期', '初创期', '发展期'],
    org: '机构概览',
    expertise: '专长',
    location: '地点',
    founded: '创立时间',
    stage: '项目进展',
    budget: '年度预算',
    staff: '全职员工数量',
    funding: '资金来源',
    investStage: '投资类型',
    investBudget: '投资额度',
    investType: '资金来源',
    returnRate: '期望回报率',
    onlySocial: '只看重社会影响力',
    onlyEconomic: '只看重经济回报',
    bothSocial: '兼顾社会影响力和经济回报，但社会影响力优先',
    bothEconomic: '兼顾社会影响力和经济回报，但经济回报优先',
    select: '投资偏好',
    plan: '计划书',
    desc: '机构详情',
    idea: '设想期',
    start: '初创期',
    scaling: '发展期',
    noLimit: '不限',
    yes: '是',
    no: '否',
    revenueDetail: ['是', '否'],
    assistance: '所需帮助',
    revenueType: '是否盈利',
  },
}

// install plugin
Vue.use(VueI18n)


// set lang
Vue.config.lang = 'en'
// set locales
Object.keys(locales).forEach(lang =>
  Vue.locale(lang, locales[lang]),
)

Vue.use(ElementUI)
Vue.prototype.$ajax = axios
/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
})
